### PR TITLE
Database Migration feature

### PR DESCRIPTION
**Pull request by antshc**
Hello @SRoddis @thiagoadril,

I have found that people looking for Database level migrations libraries and also
I use mongo migration library on the current project and we need to insert new documents from file some times, I want to use migrations for this, I have created a Pull request which enables Database level migrations.

I have updated existing naming for migrations and add Database migration functionality 
MongoMigration

I can continue to work on this topic
list of things what not finished:
- continue manual testing
- write Unit Tests
- test database migrations  when no document migrations

Is the following feature interesting for you?

### CODE REVIEW

**Comment by SRoddis** [comment]
Yes, you are welcome to work on the project. 

It is just importand that you write unit tests, check the performance and add documentation for the feature. Sounds good. :)

Cheers, Sean

**Comment by RoyalTux** [comment]
Hello @khdevnet , 

It's a very good idea to implement this feature and tests. I need this functionality in my project too. Thank you for your work!

Best regards, Dmitriy

**Comment by antshc** [comment]
> Yes, you are welcome to work on the project.
> 
> It is just importand that you write unit tests, check the performance and add documentation for the feature. Sounds good. :)
> 
> Cheers, Sean

Hello @SRoddis ,

I have added tests and update documentation.

I didn't write performance tests because I don't know what cover with them, in case of database migration, performance depends on how you write your migration.

@SRoddis 
Can you please review my latest changes and let me know what I left to do to finalize the current Pull request?

**Comment by johnnyswan** [comment]
Hey, guys, we're just looking for a similar tool for our project. Good idea.

**Pull request merged**
